-- ============================================================
--  NgEkoz — Database Schema (PostgreSQL / Supabase Edition)
--  Platform Pencarian & Sewa Kos (AUTO_INCREMENT / BIGINT ID)
-- ============================================================

-- Aktifkan ekstensi PostGIS untuk pencarian lokasi radius cepat
CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================================
--  FUNGSI GLOBAL (UPDATED_AT TRIGGER)
-- ============================================================
CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
--  SEGMENT 0 — CUSTOM TYPES (ENUMS)
-- ============================================================
CREATE TYPE user_role AS ENUM ('admin', 'owner', 'user');
CREATE TYPE user_gender AS ENUM ('laki-laki', 'perempuan');
CREATE TYPE gender_kos_type AS ENUM ('putra', 'putri', 'campur');
CREATE TYPE duration_type AS ENUM ('bulanan', 'harian');
CREATE TYPE reserve_status AS ENUM ('pending', 'waiting_payment', 'paid', 'cancelled', 'completed');
CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'expired', 'failed');
CREATE TYPE report_status AS ENUM ('menunggu', 'diproses', 'selesai', 'ditolak');
CREATE TYPE report_category AS ENUM ('penipuan', 'informasi_tidak_sesuai', 'foto_tidak_sesuai', 'kos_tidak_tersedia', 'perilaku_tidak_pantas', 'lainnya');

-- ============================================================
--  SEGMENT 1 — LOKASI
-- ============================================================

CREATE TABLE provinsi (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_provinsi VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_nama_provinsi ON provinsi (nama_provinsi);
CREATE TRIGGER set_provinsi_updated_at BEFORE UPDATE ON provinsi FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE kota (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_provinsi BIGINT NOT NULL REFERENCES provinsi (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    nama_kota VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_nama_kota ON kota (nama_kota);
CREATE TRIGGER set_kota_updated_at BEFORE UPDATE ON kota FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE kecamatan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_kota BIGINT NOT NULL REFERENCES kota (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    nama_kecamatan VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_nama_kecamatan ON kecamatan (nama_kecamatan);
CREATE TRIGGER set_kecamatan_updated_at BEFORE UPDATE ON kecamatan FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 2 — USERS
-- ============================================================

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama VARCHAR(150) NOT NULL,
    email VARCHAR(191) NOT NULL UNIQUE,
    email_verified_at TIMESTAMPTZ NULL DEFAULT NULL,
    password VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'user',
    phone VARCHAR(20) NULL DEFAULT NULL,
    profile_photo VARCHAR(500) NULL DEFAULT NULL,
    bio TEXT NULL DEFAULT NULL,
    kelamin user_gender NULL DEFAULT NULL,
    pekerjaan VARCHAR(100) NULL DEFAULT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    remember_token VARCHAR(100) NULL DEFAULT NULL,
    last_login_at TIMESTAMPTZ NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL DEFAULT NULL,
    verification_token VARCHAR(255) NULL DEFAULT NULL,
    token_expires_at TIMESTAMPTZ NULL DEFAULT NULL,
    reset_token VARCHAR(255) NULL DEFAULT NULL,
    reset_token_expires_at TIMESTAMPTZ NULL DEFAULT NULL
);
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_deleted_at ON users (deleted_at);
CREATE TRIGGER set_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 3 — MASTER FASILITAS & ATURAN
-- ============================================================

CREATE TABLE fasilitas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_fasilitas VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(100) NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER set_fasilitas_updated_at BEFORE UPDATE ON fasilitas FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE aturan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_aturan VARCHAR(200) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER set_aturan_updated_at BEFORE UPDATE ON aturan FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 4 — KOS
-- ============================================================

CREATE TABLE detail_kos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_owner BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_provinsi BIGINT NOT NULL REFERENCES provinsi (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_kota BIGINT NOT NULL REFERENCES kota (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_kecamatan BIGINT NOT NULL REFERENCES kecamatan (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    nama_kos VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL UNIQUE,
    deskripsi TEXT NULL DEFAULT NULL,
    alamat TEXT NOT NULL,
    latitude NUMERIC(10, 8) NULL DEFAULT NULL,
    longitude NUMERIC(11, 8) NULL DEFAULT NULL,
    gender_type gender_kos_type NOT NULL DEFAULT 'campur',
    rating_avg NUMERIC(3, 2) NOT NULL DEFAULT 0.00,
    total_reviews INT NOT NULL DEFAULT 0,
    view_count INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL DEFAULT NULL,
    location GEOGRAPHY(POINT, 4326) NULL -- PostGIS Optimization
);
CREATE INDEX idx_kos_owner ON detail_kos (id_owner);
CREATE INDEX idx_kos_lokasi ON detail_kos (id_provinsi, id_kota, id_kecamatan);
CREATE INDEX idx_kos_gender ON detail_kos (gender_type);
CREATE INDEX idx_kos_rating ON detail_kos (rating_avg DESC);
CREATE INDEX idx_kos_active ON detail_kos (is_active, deleted_at);
CREATE INDEX idx_kos_location_gist ON detail_kos USING GIST (location);
CREATE TRIGGER set_detail_kos_updated_at BEFORE UPDATE ON detail_kos FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE fasilitas_kos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_detail_kos BIGINT NOT NULL REFERENCES detail_kos (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id_fasilitas BIGINT NOT NULL REFERENCES fasilitas (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE (id_detail_kos, id_fasilitas)
);

CREATE TABLE aturan_kos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_detail_kos BIGINT NOT NULL REFERENCES detail_kos (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id_aturan BIGINT NOT NULL REFERENCES aturan (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE (id_detail_kos, id_aturan)
);

CREATE TABLE foto_kos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_detail_kos BIGINT NOT NULL REFERENCES detail_kos (id) ON DELETE CASCADE ON UPDATE CASCADE,
    image_url TEXT NOT NULL,
    thumbnail BOOLEAN NOT NULL DEFAULT FALSE,
    urutan SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_foto_kos ON foto_kos (id_detail_kos, thumbnail);

CREATE TABLE kamar_kos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_detail_kos BIGINT NOT NULL REFERENCES detail_kos (id) ON DELETE CASCADE ON UPDATE CASCADE,
    nomor_kamar VARCHAR(20) NOT NULL,
    ukuran VARCHAR(50) NULL DEFAULT NULL,
    deskripsi TEXT NULL DEFAULT NULL,
    price_per_month NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    price_per_day NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    total_kamar SMALLINT NOT NULL DEFAULT 1,
    kamar_tersedia SMALLINT NOT NULL DEFAULT 1,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_detail_kos, nomor_kamar)
);
CREATE INDEX idx_kamar_tersedia ON kamar_kos (id_detail_kos, is_available);
CREATE TRIGGER set_kamar_kos_updated_at BEFORE UPDATE ON kamar_kos FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 5 — RESERVASI
-- ============================================================

CREATE TABLE reservasi (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kode_reservasi VARCHAR(30) NOT NULL UNIQUE,
    id_user BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_detail_kos BIGINT NOT NULL REFERENCES detail_kos (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_kamar BIGINT NOT NULL REFERENCES kamar_kos (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    tanggal_check_in DATE NOT NULL,
    tanggal_check_out DATE NOT NULL,
    duration_values duration_type NOT NULL DEFAULT 'bulanan',
    durasi SMALLINT NOT NULL DEFAULT 1,
    tambahan_keterangan TEXT NULL DEFAULT NULL,
    harga_sewa NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    biaya_admin NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    total_harga NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    status reserve_status NOT NULL DEFAULT 'pending',
    expired_at TIMESTAMPTZ NULL DEFAULT NULL,
    cancelled_at TIMESTAMPTZ NULL DEFAULT NULL,
    cancel_reason VARCHAR(500) NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_reservasi_user ON reservasi (id_user);
CREATE INDEX idx_reservasi_kos ON reservasi (id_detail_kos);
CREATE INDEX idx_reservasi_kamar ON reservasi (id_kamar);
CREATE INDEX idx_reservasi_status ON reservasi (status);
CREATE INDEX idx_reservasi_expired ON reservasi (expired_at, status);
CREATE TRIGGER set_reservasi_updated_at BEFORE UPDATE ON reservasi FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 6 — PAYMENT
-- ============================================================

CREATE TABLE payment (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_reservasi BIGINT NOT NULL REFERENCES reservasi (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_user BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    xendit_invoice_id VARCHAR(100) NULL DEFAULT NULL,
    xendit_invoice_url VARCHAR(500) NULL DEFAULT NULL,
    payment_method VARCHAR(50) NULL DEFAULT NULL,
    bank_code VARCHAR(20) NULL DEFAULT NULL,
    amount NUMERIC(14, 2) NOT NULL DEFAULT 0.00,
    status payment_status NOT NULL DEFAULT 'pending',
    paid_at TIMESTAMPTZ NULL DEFAULT NULL,
    expired_at TIMESTAMPTZ NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_payment_reservasi ON payment (id_reservasi);
CREATE INDEX idx_payment_user ON payment (id_user);
CREATE INDEX idx_payment_status ON payment (status);
CREATE INDEX idx_payment_xendit ON payment (xendit_invoice_id);
CREATE TRIGGER set_payment_updated_at BEFORE UPDATE ON payment FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE payment_callback (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_payment BIGINT NOT NULL REFERENCES payment (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    callback_type VARCHAR(50) NOT NULL,
    payload JSONB NOT NULL,
    headers JSONB NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at TIMESTAMPTZ NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_callback_payment ON payment_callback (id_payment);
CREATE INDEX idx_callback_type ON payment_callback (callback_type);
CREATE INDEX idx_callback_verified ON payment_callback (is_verified, processed_at);
CREATE TRIGGER set_payment_callback_updated_at BEFORE UPDATE ON payment_callback FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 7 — REVIEW
-- ============================================================

CREATE TABLE review (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_detail_kos BIGINT NOT NULL REFERENCES detail_kos (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id_reservasi BIGINT NOT NULL UNIQUE REFERENCES reservasi (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    rating NUMERIC(2, 1) NOT NULL CHECK (rating BETWEEN 1.0 AND 5.0),
    comment TEXT NULL DEFAULT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_review_kos ON review (id_detail_kos);
CREATE INDEX idx_review_user ON review (id_user);
CREATE TRIGGER set_review_updated_at BEFORE UPDATE ON review FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 8 — LAPORAN
-- ============================================================

CREATE TABLE laporan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_detail_kos BIGINT NULL DEFAULT NULL REFERENCES detail_kos (id) ON DELETE SET NULL ON UPDATE CASCADE,
    jenis_laporan VARCHAR(100) NOT NULL,
    kategori report_category NOT NULL DEFAULT 'lainnya',
    deskripsi TEXT NOT NULL,
    bukti_url VARCHAR(500) NULL DEFAULT NULL,
    status_laporan report_status NOT NULL DEFAULT 'menunggu',
    catatan_admin TEXT NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_laporan_user ON laporan (id_user);
CREATE INDEX idx_laporan_kos ON laporan (id_detail_kos);
CREATE INDEX idx_laporan_status ON laporan (status_laporan);
CREATE TRIGGER set_laporan_updated_at BEFORE UPDATE ON laporan FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

-- ============================================================
--  SEGMENT 9 — PERCAKAPAN & PESAN
-- ============================================================

CREATE TABLE percakapan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_user BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_owner BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_detail_kos BIGINT NULL DEFAULT NULL REFERENCES detail_kos (id) ON DELETE SET NULL ON UPDATE CASCADE,
    last_message_at TIMESTAMPTZ NULL DEFAULT NULL,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_user, id_owner, id_detail_kos)
);
CREATE INDEX idx_percakapan_user ON percakapan (id_user, last_message_at DESC);
CREATE INDEX idx_percakapan_owner ON percakapan (id_owner, last_message_at DESC);
CREATE TRIGGER set_percakapan_updated_at BEFORE UPDATE ON percakapan FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

CREATE TABLE pesan (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_percakapan BIGINT NOT NULL REFERENCES percakapan (id) ON DELETE CASCADE ON UPDATE CASCADE,
    id_sender BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    message TEXT NOT NULL,
    attachment_url VARCHAR(500) NULL DEFAULT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ NULL DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_pesan_percakapan ON pesan (id_percakapan, created_at DESC);
CREATE INDEX idx_pesan_sender ON pesan (id_sender);
CREATE INDEX idx_pesan_unread ON pesan (id_percakapan, is_read);

-- ============================================================
--  SEGMENT 10 — LOGIC TRIGGERS (PostgreSQL Style)
-- ============================================================

-- 1. Sync Latitude/Longitude ke PostGIS Location (Detail Kos)
CREATE OR REPLACE FUNCTION sync_kos_location()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
        NEW.location = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sync_kos_location
BEFORE INSERT OR UPDATE OF latitude, longitude ON detail_kos
FOR EACH ROW EXECUTE FUNCTION sync_kos_location();

-- 2. Auto Update Rating Kos saat ada Review
CREATE OR REPLACE FUNCTION update_kos_rating()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        UPDATE detail_kos
        SET rating_avg = COALESCE((SELECT ROUND(AVG(rating), 2) FROM review WHERE id_detail_kos = OLD.id_detail_kos), 0.00),
            total_reviews = (SELECT COUNT(*) FROM review WHERE id_detail_kos = OLD.id_detail_kos)
        WHERE id = OLD.id_detail_kos;
        RETURN OLD;
    ELSE
        UPDATE detail_kos
        SET rating_avg = COALESCE((SELECT ROUND(AVG(rating), 2) FROM review WHERE id_detail_kos = NEW.id_detail_kos), 0.00),
            total_reviews = (SELECT COUNT(*) FROM review WHERE id_detail_kos = NEW.id_detail_kos)
        WHERE id = NEW.id_detail_kos;
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_review_after_insert_update
AFTER INSERT OR UPDATE ON review
FOR EACH ROW EXECUTE FUNCTION update_kos_rating();

CREATE TRIGGER trg_review_after_delete
AFTER DELETE ON review
FOR EACH ROW EXECUTE FUNCTION update_kos_rating();

-- 3. Auto Update last_message_at di Percakapan
CREATE OR REPLACE FUNCTION update_percakapan_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE percakapan
    SET last_message_at = NEW.created_at
    WHERE id = NEW.id_percakapan;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pesan_after_insert
AFTER INSERT ON pesan
FOR EACH ROW EXECUTE FUNCTION update_percakapan_timestamp();

-- 4. Auto Update Ketersediaan Kamar dari Status Reservasi
CREATE OR REPLACE FUNCTION update_kamar_tersedia()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        -- Jika bayar, kurangi stok
        IF NEW.status = 'paid' AND OLD.status != 'paid' THEN
            UPDATE kamar_kos
            SET kamar_tersedia = GREATEST(0, kamar_tersedia - 1),
                is_available = CASE WHEN (kamar_tersedia - 1) > 0 THEN TRUE ELSE FALSE END
            WHERE id = NEW.id_kamar;
        END IF;
        -- Jika selesai/batal, kembalikan stok
        IF NEW.status IN ('completed', 'cancelled') AND OLD.status = 'paid' THEN
            UPDATE kamar_kos
            SET kamar_tersedia = kamar_tersedia + 1,
                is_available = TRUE
            WHERE id = NEW.id_kamar;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reservasi_after_update
AFTER UPDATE ON reservasi
FOR EACH ROW EXECUTE FUNCTION update_kamar_tersedia();